### ISSUE TITLE
Spoor ID cookie

### ISSUE THREAD

**Issue by markstephens** [Financial-Times/spoor-api#36]
A slight issue with the Spoor ID cookie.

This is the scenario:

1. The preflight `OPTIONS` request is made by the browser to confirm CORS is allowed.
    - Cookies aren't sent with this request, maybe because the headers don't allow it
    - OR I've read some browsers don't send cookies on the `OPTIONS` request regardless.
2. Spoor API responds with a new cookie as it didn't receive one.
    - This means the spoor id cookie is being continuously overwritten on each page load.

I think the answer is to only set the cookie on `POST` or `GET` requests. As cookies on the `OPTIONS` request are unreliable.

**Comment by commuterjoy** [comment]
Good spot. Will fix this ASAP.
