### ISSUE TITLE
Provide a pageview.gif utility endpoint

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/spoor-api#59]
```
https://spoor-api.ft.com/px.gif?data=%7b%22category%22%3a%22page%22%2c%22action%22%3a%22view%22%2c%22system%22%3a%7b%22source%22%3a%22non-ctm%22%7d%2c%22user%22%3a%7b%7d%2c%22context%22%3a%7b%22product%22%3a%22next%22%7d%7d
```
Is verbose, easy to mess up and now needs to be duplicated in the page https://github.com/Financial-Times/o-tracking/issues/83#issuecomment-176259273

I suggest something like `/page-view/:product.gif` route to make the non-ctm fallback for o-tracking easier to write.

**Comment by commuterjoy** [comment]
If we had to, I'd prefer query strings and that feels more extensible ...

`https://spoor-api.ft.com/px.gif?product=next&category=view&action=...`

**Comment by wheresrhys** [comment]
I wouldn't want to do that as the data object can have nested properties, so query stringing it could be just as error prone as having an encoded JSON.

It also wouldn't address the main advantage (as I see it) of `/page-view/{product}.gif`, which is to protect the lay front-end developer from all the domain specific terminology of o-tracking/spoor

**Comment by commuterjoy** [comment]
closing until more obvious use case presents itself.
