### ISSUE TITLE
Enchrichment

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-api#7]
In order to accept arbitrary events but enrich them we need some standards on what the incoming data looks like.

Enrichment is only available to clients sending JSON.

Eg, 

- if the event contains a `user.ftsession` the event will be expanded to an guid (or a invalid session).
- if the event contains a `content.uuid` we decorate the event with content API data.
- ... contains `user.ip` then we hit maxmind.
- ... contains `user.ua` then we expand the data to device atlas.

**Comment by commuterjoy** [comment]
Question :-

 - How do the enrichments decorate the JSON structure?
 - How do we QA and/or limit the amount of stuff being enriched (we can't have 10MB of enriched data)
 - Is a failed enrichment a complete failure (and need to be reprocessed?). Eg. consider an CAPI outage.

**Comment by markstephens** [comment]
**How do the enrichments decorate the JSON structure?**
We need to make sure there's no risk of overwriting existing values, maybe all the enrichments are namespaced in an enrichments object?

**How do we QA and/or limit the amount of stuff being enriched?**
Yeah, good question, my guess is we need a specific requirement for each enrichment/value? Means the enrichment process would have to cherry-pick many different values out of the APIs which might end up fiddly.

**Is a failed enrichment a complete failure (and need to be reprocessed?)?**
Leaning towards yes.
- Some of the data warehouse enrichments will be relying on stream enriched values being present.
- I don't think we want to get into failing or succeeding under different enrichment failure conditions (e.g. fail on failed user lookup but succeed anyway on failed capi lookup) - That would get complex?

**Should we care about non-JSON clients.**
No, I think we can make all our clients send something that looks like JSON, whether it's POSTed or a GET with ?d={ .. json .. }

**Comment by commuterjoy** [comment]
Dealt with all of this.
