### ISSUE TITLE
Healthcheck should always respond with 200

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-api#96]
unless the route is borked.

**Comment by martinroddam** [comment]
Actually, if you did make the change to this service to conform to the FT health check standard, Pingdom checks would be rendered useless if they expect a non-200 status code to represent a failure. In this case, you're better off *not* conforming to the standard.

**Comment by commuterjoy** [comment]
yeah, i'm going to close this as I like pingdom telling me stuff has gone wrong.
